version: '2'
services:
  extractor:
    depends_on:
      - elastic
      - redis
    build:
      context: .
      dockerfile: Extractor.Dockerfile
    volumes:
      - ./src:/home/ExtractorAPI
    ports:
      - "8000:8000"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redisdata:/data
    entrypoint: redis-server --appendonly yes
    restart: always