version: '2'
services:
  extractor:
    depends_on:
      - redis
      - elastic
    build:
      context: .
      dockerfile: Extractor.Dockerfile
    volumes:
      - ./:/home/ExtractorAPI
    ports:
      - 8000:8000

  celery:
    depends_on:
      - elastic
      - redis
    build:
      context: .
      dockerfile: Celery.Dockerfile
    volumes:
      - ./:/home/ExtractorAPI
    restart: always
      
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redisdata:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    depends_on:
      - elastic
    environment:
      SERVER_PORT: 5601
      ELASTICSEARCH_URL: http://elastic:9200/
    ports:
      - 5601:5601